/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hp.school.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the School service. Represents a row in the &quot;sch_School&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hp.school.management.model.impl.SchoolModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hp.school.management.model.impl.SchoolImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see School
 * @generated
 */
@ProviderType
public interface SchoolModel extends BaseModel<School> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a school model instance should use the {@link School} interface instead.
	 */

	/**
	 * Returns the primary key of this school.
	 *
	 * @return the primary key of this school
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this school.
	 *
	 * @param primaryKey the primary key of this school
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this school.
	 *
	 * @return the uuid of this school
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this school.
	 *
	 * @param uuid the uuid of this school
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the school ID of this school.
	 *
	 * @return the school ID of this school
	 */
	public long getSchoolId();

	/**
	 * Sets the school ID of this school.
	 *
	 * @param schoolId the school ID of this school
	 */
	public void setSchoolId(long schoolId);

	/**
	 * Returns the group ID of this school.
	 *
	 * @return the group ID of this school
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this school.
	 *
	 * @param groupId the group ID of this school
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the name of this school.
	 *
	 * @return the name of this school
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this school.
	 *
	 * @param name the name of this school
	 */
	public void setName(String name);

	/**
	 * Returns the type of this school.
	 *
	 * @return the type of this school
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this school.
	 *
	 * @param type the type of this school
	 */
	public void setType(String type);

	/**
	 * Returns the city of this school.
	 *
	 * @return the city of this school
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this school.
	 *
	 * @param city the city of this school
	 */
	public void setCity(String city);

	/**
	 * Returns the no ofstudent of this school.
	 *
	 * @return the no ofstudent of this school
	 */
	public int getNoOfstudent();

	/**
	 * Sets the no ofstudent of this school.
	 *
	 * @param noOfstudent the no ofstudent of this school
	 */
	public void setNoOfstudent(int noOfstudent);

	/**
	 * Returns the created by of this school.
	 *
	 * @return the created by of this school
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this school.
	 *
	 * @param createdBy the created by of this school
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the updated by of this school.
	 *
	 * @return the updated by of this school
	 */
	public long getUpdatedBy();

	/**
	 * Sets the updated by of this school.
	 *
	 * @param updatedBy the updated by of this school
	 */
	public void setUpdatedBy(long updatedBy);

	/**
	 * Returns the create date of this school.
	 *
	 * @return the create date of this school
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this school.
	 *
	 * @param createDate the create date of this school
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this school.
	 *
	 * @return the modified date of this school
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this school.
	 *
	 * @param modifiedDate the modified date of this school
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the is active of this school.
	 *
	 * @return the is active of this school
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this school is is active.
	 *
	 * @return <code>true</code> if this school is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this school is is active.
	 *
	 * @param isActive the is active of this school
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the status of this school.
	 *
	 * @return the status of this school
	 */
	public int getStatus();

	/**
	 * Sets the status of this school.
	 *
	 * @param status the status of this school
	 */
	public void setStatus(int status);

}